name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: cd atendimentos-api && npm ci
    - name: Run Supertest tests
      run: cd atendimentos-api && npm test
    - name: Run Newman tests
      run: cd atendimentos-api && npm run test:postman

  test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: cd chatbot-sut && npm ci
    - name: Install Cypress
      run: cd chatbot-sut && npm install cypress @badeball/cypress-cucumber-preprocessor @bahmutov/cypress-esbuild-preprocessor
    - name: Run Cypress tests
      run: cd chatbot-sut && npm run test

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [test-api, test-frontend]
    steps:
    - uses: actions/checkout@v3
    - name: Build frontend
      run: cd chatbot-sut/frontend && npm ci && npm run build
    - name: Upload frontend build
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: chatbot-sut/frontend/dist/
    - name: Build backend
      run: cd chatbot-sut/backend && npm ci --only=production
    - name: Upload backend
      uses: actions/upload-artifact@v3
      with:
        name: backend-build
        path: chatbot-sut/backend/
    - name: Build API
      run: cd atendimentos-api && npm ci --only=production
    - name: Upload API
      uses: actions/upload-artifact@v3
      with:
        name: api-build
        path: atendimentos-api/