name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies for API
      run: |
        cd atendimentos-api
        npm ci
        
    - name: Install dependencies for Frontend
      run: |
        cd chatbot-sut
        npm ci
        
    - name: Build and start API
      run: |
        cd atendimentos-api
        npm run build
        npm start &
        echo "Waiting for API to start..."
        sleep 15
        
    - name: Start Frontend
      run: |
        cd chatbot-sut
        npm run dev &
        echo "Waiting for frontend to start..."
        sleep 15
        
    - name: Install Newman
      run: npm install -g newman
        
    - name: Run Postman tests
      run: |
        cd atendimentos-api
        echo '{
          "id": "env-atendimentos-ci",
          "name": "Atendimentos Environment CI",
          "values": [
            {
              "key": "baseUrl",
              "value": "http://localhost:5000",
              "enabled": true
            }
          ]
        }' > postman_environment_ci.json
        newman run postman_collection.json --environment postman_environment_ci.json
        
    - name: Run Cypress tests
      run: |
        cd chatbot-sut
        npm run test:ci

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          chatbot-sut/cypress/videos/
          chatbot-sut/cypress/screenshots/
          atendimentos-api/newman/