name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd atendimentos-api && npm ci
        cd ../chatbot-sut && npm ci
        
    - name: Start services with Docker Compose
      run: |
        docker compose up -d
        sleep 10  # Aguarda os serviços iniciarem
        
    - name: Install Newman
      run: npm install -g newman
        
    - name: Run Postman tests
      run: |
        cd atendimentos-api
        echo '{
          "id": "env-atendimentos-ci",
          "name": "Atendimentos Environment CI",
          "values": [
            {
              "key": "baseUrl",
              "value": "http://localhost:5000",
              "enabled": true
            }
          ]
        }' > postman_environment_ci.json
        newman run postman_collection.json --environment postman_environment_ci.json
        
    - name: Run Cypress tests
      run: |
        cd chatbot-sut
        export CYPRESS_BASE_URL=http://localhost
        npm run test

    - name: Stop services
      if: always()
      run: docker compose down